version: '3.8'

services:
  order-voice-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-voice-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
    env_file:
      - .env.v2
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - order-voice-network

networks:
  order-voice-network:
    driver: bridge
