version: '3.8'

services:
  order-voice-backend-basic:
#    image: backend-order-voice-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nola-backend-basic
    ports:
      - "8005:8001"
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
    env_file:
      - .env.prod
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - traefik-networks
    labels:
      - "traefik.docker.network=traefik-networks"
      - "traefik.enable=true"
      - "traefik.http.routers.nolabebasic.rule=Host(`bebasic.nola.ai.vn`)"
#      - "traefik.http.services.nolabebasic.loadbalancer.server.port=8001"
      - "traefik.http.routers.nolabebasic.entrypoints=websecure"
      - "traefik.http.routers.nolabebasic.tls=true"
      - "traefik.http.routers.nolabe.tls.certresolver=teableresolver"
#     - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
#     - "traefik.http.routers.nolabebasic.middlewares=redirect@docker"

networks:
  traefik-networks:
    external: true
